name: infra-markkyn
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=http://my.markkyn.com/
     - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
     - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
     - 'grafana_storage:/var/lib/grafana'
    networks:
      - network-zabbix
    links:
      - zabbix-mysql
      - zabbix-server
    depends_on:
      - zabbix-mysql
      - zabbix-server

include:
  # Password management
  - services/passbolt/docker-compose-ce.yaml # PassBolt
  # Gaming
  - services/gaming/docker-compose.yaml # Minecraft
  # Automation
  - services/automation/docker-compose.yaml # n8n
  # Network
  - services/network/docker-compose.yaml # Zabbix

volumes:
  grafana_storage: {}